Add python2 version as a binary, fix virtualenv support for python3

diff --git a/bin/foodProcessor2 b/bin/foodProcessor2
--- a/bin/foodProcessor2
+++ b/bin/foodProcessor2
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-command -v python3 >/dev/null 2>&1 || { echo "I require python3 but it's not installed. Maybe try foodprocessor2 instead for python2 support." >&2; exit 1; }
+command -v virtualenv >/dev/null 2>&1 || { echo "I require virtualenv but it's not installed.  Aborting." >&2; exit 1; }
 
 basepath=$(dirname $(realpath $0))
 fp_path=${basepath%bin}
@@ -9,9 +9,9 @@ venv_path=${fp_path}venv/bin/
 if [ ! -e $venv_path ]; then
   echo "No venv directory found, installing required modules...\n\n"
   cd $fp_path
-  python3 -m virtualenv venv
+  virtualenv venv
   ${venv_path}pip install -r requirements.txt
   echo "Installation complete, running app...\n\n"
 fi
 
-${venv_path}python3 ${fp_path}foodProcessor.py $@
+${venv_path}python ${fp_path}foodProcessor.py $@
